// <auto-generated />
using System;
using Ambev.DeveloperEvaluation.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambev.DeveloperEvaluation.WebApi.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250430005903_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Branch", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e46bb862-2076-4d46-9155-749f48648f2e"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 791, DateTimeKind.Utc).AddTicks(7389),
                            Email = "mail@mail.com",
                            Name = "branch 1",
                            Phone = "1111111111"
                        },
                        new
                        {
                            Id = new Guid("9d84f0d1-38fa-473a-a06f-2281ca179f51"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 791, DateTimeKind.Utc).AddTicks(7392),
                            Email = "mail@mail.com",
                            Name = "branch 2",
                            Phone = "1111111111"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d78d9a8d-bbc1-46c3-b4c3-0a2798f74c40"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(107),
                            Email = "mail@mail.com",
                            Name = "customer 1",
                            Phone = "1111111111"
                        },
                        new
                        {
                            Id = new Guid("605b5fa5-3b1c-4b25-92de-1c46ffe19fa1"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(109),
                            Email = "mail@mail.com",
                            Name = "customer 2",
                            Phone = "1111111111"
                        },
                        new
                        {
                            Id = new Guid("b92201f4-b459-45d5-9ef3-1d9455bf123f"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(111),
                            Email = "mail@mail.com",
                            Name = "customer 3",
                            Phone = "1111111111"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("MinimumUnits")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0fa1ae7-2801-44ef-8402-5ea4d0c7f8c6"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(2401),
                            DiscountPercentage = 10m,
                            MinimumUnits = 4
                        },
                        new
                        {
                            Id = new Guid("17c2e1f1-94f9-4d00-bab0-8273aee78790"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(2403),
                            DiscountPercentage = 20m,
                            MinimumUnits = 10
                        },
                        new
                        {
                            Id = new Guid("b551c293-bb06-4dc4-ae9b-bc4ab7e5fef9"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(2406),
                            DiscountPercentage = 0m,
                            MinimumUnits = 21
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BarCodeGTIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c4de8ee-752d-4628-98d2-c4e41ba4d871"),
                            BarCodeGTIN = "7891991000840",
                            Code = "1201048",
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(7226),
                            Description = "Agua Tonica",
                            Name = "Agua Tonica Lata 350Ml Antartica"
                        },
                        new
                        {
                            Id = new Guid("996c81d9-6726-471b-9e47-8b1009e0691b"),
                            BarCodeGTIN = "7891042000201",
                            Code = "1121285",
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(7233),
                            Description = "Cha gelado",
                            Name = "Cha Tea Zero 1,5Lt Lipton Limao"
                        },
                        new
                        {
                            Id = new Guid("ff41c778-3de5-4148-a71b-31babac65964"),
                            BarCodeGTIN = "7892840822019",
                            Code = "1277098",
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 792, DateTimeKind.Utc).AddTicks(7235),
                            Description = "Isotonico",
                            Name = "Isotonico Gatorade 500Ml Blueberry"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<bool>("Open")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RecommendedSellerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseOrder", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FullPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("UnitId");

                    b.ToTable("PurchaseOrderProduct", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<bool>("Open")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendedSellerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.SaleProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FullPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("UnitId");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b8cb3c-b60e-44b1-a494-f5ce9fad92e1"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(19),
                            Description = "Unit",
                            Name = "UN"
                        },
                        new
                        {
                            Id = new Guid("8b3310f7-05cb-4530-917b-f7824edf8584"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(21),
                            Description = "Package",
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SellerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41e3de69-4265-43c6-a2d1-9657979160d2"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3287),
                            Email = "developer@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Admin",
                            SellerCode = "",
                            Status = "Active",
                            Username = "developer"
                        },
                        new
                        {
                            Id = new Guid("d7081c09-0bba-4728-b4e5-804c73a6d1b8"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3290),
                            Email = "admin@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Admin",
                            SellerCode = "",
                            Status = "Active",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("f16dcf3f-c13c-413a-a73d-cc297c0e53a0"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3292),
                            Email = "manager@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Manager",
                            SellerCode = "",
                            Status = "Active",
                            Username = "manager"
                        },
                        new
                        {
                            Id = new Guid("24315cc0-f77d-48ae-a0c1-56cfa851491a"),
                            BranchId = new Guid("e46bb862-2076-4d46-9155-749f48648f2e"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3294),
                            Email = "branch1user1@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Branch",
                            SellerCode = "",
                            Status = "Active",
                            Username = "branch1-user1"
                        },
                        new
                        {
                            Id = new Guid("98004d1c-87c7-40d4-b873-43aa8524bbf7"),
                            BranchId = new Guid("e46bb862-2076-4d46-9155-749f48648f2e"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3299),
                            Email = "branch1user2@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Branch",
                            SellerCode = "",
                            Status = "Active",
                            Username = "branch1-user2"
                        },
                        new
                        {
                            Id = new Guid("f43616fd-c39e-40aa-b57f-b97c3937d849"),
                            BranchId = new Guid("9d84f0d1-38fa-473a-a06f-2281ca179f51"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3303),
                            Email = "branch2user1@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Branch",
                            SellerCode = "",
                            Status = "Active",
                            Username = "branch2-user1"
                        },
                        new
                        {
                            Id = new Guid("51372e2d-00ed-475f-9cbb-f8debff265b4"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3305),
                            CustomerId = new Guid("d78d9a8d-bbc1-46c3-b4c3-0a2798f74c40"),
                            Email = "customer1user1@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Customer",
                            SellerCode = "",
                            Status = "Active",
                            Username = "customer1-user1"
                        },
                        new
                        {
                            Id = new Guid("5640e90f-ddc7-497f-821e-7aff79c34238"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3308),
                            CustomerId = new Guid("d78d9a8d-bbc1-46c3-b4c3-0a2798f74c40"),
                            Email = "customer1user2@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Customer",
                            SellerCode = "",
                            Status = "Active",
                            Username = "customer1-user2"
                        },
                        new
                        {
                            Id = new Guid("8320f1b2-32a2-409f-88df-bd60a83723de"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3311),
                            CustomerId = new Guid("605b5fa5-3b1c-4b25-92de-1c46ffe19fa1"),
                            Email = "customer2user1@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Customer",
                            SellerCode = "",
                            Status = "Active",
                            Username = "customer2-user1"
                        },
                        new
                        {
                            Id = new Guid("a28d70c5-1b17-4913-87e6-e1e18f65571b"),
                            CreatedAt = new DateTime(2025, 4, 30, 0, 59, 2, 795, DateTimeKind.Utc).AddTicks(3313),
                            CustomerId = new Guid("b92201f4-b459-45d5-9ef3-1d9455bf123f"),
                            Email = "customer3user1@mail.com",
                            Password = "$2a$11$kYfspCSu4jJk55A/NynhtOahhlgPwki3SSlyusVQTjqZ.rLYbIrg.",
                            Phone = "1111111111",
                            Role = "Customer",
                            SellerCode = "",
                            Status = "Active",
                            Username = "customer3-user1"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Price", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BranchUserId");

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrderProduct", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Price", null)
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BranchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerUserId");

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Price", null)
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.User", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
